#!/usr/bin/env python3
import hashlib
import re
import subprocess
from pathlib import Path

EXPECTED_MLKEM_NATIVE_KAT_SHA256 = "0a2d61707a68c0cac7b2a5005def19994e4e2a25cf8dc512b1254cbaa25473c0"

ROOT = Path(__file__).resolve().parents[1]
MLKEM_NATIVE_DIR = ROOT / "external" / "mlkem-native"
GEN_KAT = MLKEM_NATIVE_DIR / "test" / "build" / "mlkem512" / "bin" / "gen_KAT512"
OUT = ROOT / "src" / "main" / "c" / "murax" / "crystal_kyber" / "src" / "kat_vectors.h"


def run(cmd: list[str], cwd: Path) -> None:
    print(f"$ {' '.join(cmd)}")
    subprocess.run(cmd, cwd=cwd, check=True)


def first_vector(kat_output: str) -> dict[str, bytes]:
    fields: dict[str, bytes] = {}
    for name in ("pk", "sk", "ct", "ss"):
        match = re.search(rf"^{name} = ([0-9a-fA-F]+)$", kat_output, re.MULTILINE)
        if not match:
            raise SystemExit(f"missing {name} in mlkem-native KAT output")
        fields[name] = bytes.fromhex(match.group(1))
    return fields


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for index in range(0, len(data), 12):
        chunk = data[index:index + 12]
        suffix = "," if index + 12 < len(data) else ""
        lines.append("  " + ", ".join(f"0x{byte:02X}" for byte in chunk) + suffix)
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if not MLKEM_NATIVE_DIR.exists():
        raise SystemExit("missing external/mlkem-native; run: git submodule update --init --recursive")

    run(["make", "-C", str(MLKEM_NATIVE_DIR), "kat_512"], ROOT)

    output = subprocess.run([str(GEN_KAT)], cwd=ROOT, check=True, stdout=subprocess.PIPE).stdout
    digest = hashlib.sha256(output).hexdigest()
    print(f"mlkem_native_kat_sha256={digest}")
    if digest != EXPECTED_MLKEM_NATIVE_KAT_SHA256:
        raise SystemExit(
            f"unexpected mlkem-native KAT SHA-256: got {digest}, expected {EXPECTED_MLKEM_NATIVE_KAT_SHA256}"
        )

    fields = first_vector(output.decode("ascii"))

    seed = bytes(range(32, 96))
    coins0 = hashlib.shake_256(seed).digest(96)
    coins1 = hashlib.shake_256(coins0).digest(96)
    fields["keypair_coins"] = coins1[:64]
    fields["enc_coins"] = coins1[64:96]

    expected_sizes = {
        "keypair_coins": 64,
        "enc_coins": 32,
        "pk": 800,
        "sk": 1632,
        "ct": 768,
        "ss": 32,
    }
    for name, size in expected_sizes.items():
        actual = len(fields[name])
        if actual != size:
            raise SystemExit(f"unexpected {name} size: got {actual}, expected {size}")

    content = [
        "#ifndef MLKEM512_KAT_VECTORS_H",
        "#define MLKEM512_KAT_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        "/* First vector generated by external/mlkem-native/test/src/gen_KAT.c for ML-KEM-512. */",
        "/* Full generator SHA-256: " + digest + " */",
        c_array("kat_keypair_coins", fields["keypair_coins"]),
        "",
        c_array("kat_enc_coins", fields["enc_coins"]),
        "",
        c_array("kat_pk", fields["pk"]),
        "",
        c_array("kat_sk", fields["sk"]),
        "",
        c_array("kat_ct", fields["ct"]),
        "",
        c_array("kat_ss", fields["ss"]),
        "",
        "#endif",
        "",
    ]
    OUT.write_text("\n".join(content))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
